name: Deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Run App
    runs-on: ubuntu-latest
    steps:
      - name: Download files from git
        uses: actions/checkout@v2
      - name: Build app
        run: mvn package --file pom.xml
      - name: Download project as artifact
        uses: actions/upload-artifact@master
        with:
          name: mspr
          path: ./dist
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: mspr
          path: ./dist

      - name: Deploy project with SSH
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: 22
          SOURCE: "mspr.jar"
          TARGET: "~/"
